Add Text Perturbations, Transforms, Metrics, etc.
Adversarial-Deep-Learning/code-soup pull request #59
Opened 2021-08-21 09:38 UTC by abheesht17

2021-08-21 11:05 UTC, someshsingh22 requested changes
@abheesht17 We dont need transforms and extractor, they will be a part of the attack algorithm, so should be present there,

We only need the perturbations, and we dont want to use tensorflow either, altho its just the hub, its preferred to use pytorch to avoid confusion, you can use USE from FAIR https://paperswithcode.com/paper/universal-sentence-encoder

Also use unittest module instead of pytest for testing

2021-08-21 13:31 UTC, abheesht17 commented
Okay, will make the necessary modifications.

2021-08-28 14:28 UTC, abheesht17 commented
@someshsingh22, have a look.

2021-08-30 12:36 UTC, someshsingh22 approved these changes

2021-08-30 12:38 UTC, merged